USE [master]
GO

/****** Object:  Database [DbMovCon]    Script Date: 16/06/2023 10:32:43 ******/
CREATE DATABASE [DbMovCon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DbMovCon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DbMovCon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DbMovCon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DbMovCon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbMovCon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DbMovCon] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DbMovCon] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DbMovCon] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DbMovCon] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DbMovCon] SET ARITHABORT OFF 
GO

ALTER DATABASE [DbMovCon] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DbMovCon] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DbMovCon] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DbMovCon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DbMovCon] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DbMovCon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DbMovCon] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DbMovCon] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DbMovCon] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DbMovCon] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DbMovCon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DbMovCon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DbMovCon] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DbMovCon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DbMovCon] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DbMovCon] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DbMovCon] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DbMovCon] SET RECOVERY FULL 
GO

ALTER DATABASE [DbMovCon] SET  MULTI_USER 
GO

ALTER DATABASE [DbMovCon] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DbMovCon] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DbMovCon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DbMovCon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DbMovCon] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DbMovCon] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DbMovCon] SET  READ_WRITE 
GO


